/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mx7_encodingtest_NDK */

#ifndef _Included_com_mx7_encodingtest_NDK
#define _Included_com_mx7_encodingtest_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mx7_encodingtest_NDK
 * Method:    scanning
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mx7_encodingtest_NDK_scanning
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
